version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
      - run:
          name: Get IP and append it to inventory
          command: |
            mkdir -p /temp/workspace
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project,Values=udacity" \
            --output text >> inventory
      - run:
          name: Install tar/gzip utility
          command: |
            yum install -y tar gzip
            
      - persist_to_workspace:
          root: /temp/workspace
          paths: 
            - inventory
            - main-remote.yml

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["c6:67:d6:c8:31:80:f0:7d:2c:bc:b7:8a:2d:71:7e:5e"]
      - attach_workspace:
          at: /temp/workspace

      - run:
          name: Install Ansible
          command: |
            # Install Ansible
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml

workflows:
  myWorkflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          requires:
            - create_infrastructure