
version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  test-command:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id
          
workflows:
  say-hello-workflow:
    jobs:
      - test-command
