
version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
      - run: return 1
jobs:
  test-command:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id
      - run:
          name: Upload Failed Tests
          command: curl --data fail_tests.log http://example.com/error_logs
          when: on_fail
          
workflows:
  say-hello-workflow:
    jobs:
      - test-command
